name: "Remote Github Workflow"
description: |
  Trigger a remote github workflow.
  Optionally: wait for remote workflow to finish successfully.
author: "Stefan Sold"
inputs:
  workflow_id:
    required: true
    description: |
      The filename of the workflow you want to trigger.
  repository_owner:
    required: true
    description: |
      The owner of the remote repository in which the workflow resides.
    default: BAHAG
  repository_name:
    required: true
    description: |
      The name of the remote repository in which the workflow resides.
  ref:
    required: true
    description: |
      The name of the reference branch of the remote repository.
  github_token:
    required: true
    description: |
      Token to authenticate against the workflow call authorization.
  wait:
    description: |
      Wait for the remote Workflow to finish successfully.
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Trigger Workflow
      shell: bash
      run: |
        ${{ github.action_path }}/trigger_github_actions.sh \
        ${{ inputs.repository_owner }} \
        ${{ inputs.repository_name }} \
        ${{ inputs.repository_name }} \
        ${{ inputs.ref }}
    - name: Wait for Workflow to finish successfully
      if: ${{ inputs.wait == 'true' }}
      shell: bash
      run: |
        ${{ github.action_path }}/wait_for_workflow.sh \
        ${{ inputs.repository_owner }} \
        ${{ inputs.repository_name }} \
        ${{ inputs.repository_name }} \
        ${{ inputs.ref }}
